### ISSUE TITLE
libcxx must be defined for poco to build

### ISSUE THREAD

**Issue by catskul** [memsharded/four-c-example#1]
`conan install .. -s compiler=clang -s compiler.version=3.8 --build`

returns:

`ERROR: Poco/1.7.2@lasote/stable: 'settings.compiler.libcxx' value not defined`

Solved by:

`conan install .. -s compiler=clang -s compiler.version=3.8 -s compiler.libcxx=libstdc++ --build`

**Comment by memsharded** [comment]
Hi!
This doesn't really seem an issue of the repo, more an issue of the Readme, right? I will fix it. Next time, you can directly modify it and do a PR!
Many thanks for reporting!

**Comment by catskul** [comment]
Will do. I'm new to Conan.io so wasn't sure if having to list the libcxx was a work around, or expected behavior.

**Comment by memsharded** [comment]
Yes, expected behavior, it was a mistake in the readme :)

**Comment by uilianries** [comment]
I think this issue could be closed
